//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donation
    {
        public int d_id { get; set; }
        public double d_amount { get; set; }
        public string d_cause { get; set; }
        public Nullable<int> u_id_fk { get; set; }
        public Nullable<int> n_id_fk { get; set; }
    
        public virtual foundation foundation { get; set; }
        public virtual foundation foundation1 { get; set; }
        public virtual foundation foundation2 { get; set; }
        public virtual foundation foundation3 { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
        public virtual user user3 { get; set; }
    }
}
