//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foundation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public foundation()
        {
            this.donations = new HashSet<donation>();
            this.donations1 = new HashSet<donation>();
            this.donations2 = new HashSet<donation>();
            this.donations3 = new HashSet<donation>();
        }
    
        public int n_id { get; set; }
        public string n_name { get; set; }
        public Nullable<int> a_id_fk { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual admin admin1 { get; set; }
        public virtual admin admin2 { get; set; }
        public virtual admin admin3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donation> donations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donation> donations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donation> donations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donation> donations3 { get; set; }
    }
}
