//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NGO_FoundationEntities9 : DbContext
    {
        public NGO_FoundationEntities9()
            : base("name=NGO_FoundationEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<donation> donations { get; set; }
        public virtual DbSet<foundation> foundations { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
